### PR TITLE
Android Style

### PR DESCRIPTION
**Pull request by jimmyfnugent**
First steps towards adhering to Android style. I realize we don't have a style guide yet (that's #8), but there are two main things I did here:

1) Replace all tabs with spaces.
2) Tabs are 4 spaces. Also, line continuations are 8 additional spaces.

If y'all don't have AS set like this already, please update it!

This is part of #29.

### CODE REVIEW

**Comment by jimmyfnugent** [comment]
Also, oh my god this is the worst file diffing I've ever seen.

**Comment by apmcleod** [comment]
LGTM (Tip: apparently, adding ?w=1 to the end of the url diffs ignoring whitespace)

**Comment by 5centmike** [comment]
This is good. Yes. Good job! Also, ProTip! Add .patch or .diff to the end of URLs for Git's plaintext views.

delete

Also, delete one line. It doesn't matter which one, just pick a random one.

**Comment by hopskipnfall** [comment]
Nope. that diff looks so bad I'm not even going to read the changes. LGTM.

**Pull request merged**
